export const APIID = {
    EVENT_CREATE: "api.event.create",
    EVENT_LIST: "api.event.list",
    EVENT_GET: "api.event.get",
    EVENT_DELETE: "api.event.delete",
    EVENT_UPDATE: "api.event.update",
    ATTENDEES_CREATE: "api.attendees.create",
    ATTENDEES_UPDATE: "api.attendees.update",
    ATTENDEES_LIST: "api.attendees.list",
    ATTENDEES_DELETE: "api.attendees.delete",
    MEETING_LIST: "api.meeting.list",
    MEETING_UPDATE: "api.meeting.update",
    MEETING_GET: "api.meeting.get",
    ONLINE_PROVIDER: "api.meetingProvide.get",
}
